### PR TITLE
Replaces deprecated `try!` macro for `?` operator.

### PR DESCRIPTION
**Pull request by gpestana**

### CODE REVIEW

**Comment by bestouff** [comment]
In the meantime, does anyone have a workaround to eliminate the warning without vendoring `rouille` ? No amount of `#[allow(deprecated)]` around the `post_input!` macro does help.

**Comment by oherrala** [comment]
This is probably duplicate of #225. Both change 32 lines, but I didn't compare every line.

**Comment by nikodemus** [comment]
`#![allow(deprecated)]` on the toplevel of the file, before the `use` of rouille works.

Note the bang: `#!`

...but that's a big hammer and silences all deprecation notes for the file, not just the rouille one.

**Comment by bestouff** [comment]
Well, `#![allow(deprecated)]` at the very first line doesn't silence the warning in my code.

**Comment by nikodemus** [comment]
Huh, works for me. I'm still on rustc 1.40.0, though.

**Comment by bestouff** [comment]
(See previous comment, edited)

**Comment by kalj** [comment]
> This is probably duplicate of #225. Both change 32 lines, but I didn't compare every line.

Yeah, exact duplicate of #225.

**Comment by bradfier** [comment]
The earlier PR #225 was cherry picked as 1096f2bceb641ea82c186760b8727ed61a93872b, thanks for the submission anyway!

**Comment by gpestana** [comment]
Thanks @bradfier !

**Pull request closed without merging**
