### PR TITLE
Fix some TODOs in Request and Content Encoding

### PR DESCRIPTION
**Pull request by svenvdvoort**
Hello there!

With some time on my hands currently, I decided to fix some TODOs throughout the code base of Rouille.

Let me know what you think. :)

Cheers,
Sven.

### CODE REVIEW

**Comment by bradfier** [comment]
@svenvdvoort thanks for looking at these TODOs, I'm sorry it's taken so long for someone to look at your PR.

Could you rebase onto `master` and I'll review it once that's done?

**Comment by svenvdvoort** [comment]
Not a problem @bradfier , Thanks for considering my Pull Request.
I've rebased my changed on the current master branch, so you can take a look.

**Comment by svenvdvoort** [comment]
@bradfier Yess, just rebased again to the latest master.

**Comment by bradfier** [comment]
Thanks!

**Pull request merged**
