### PR TITLE
Update time 0.3 and postgres 0.19

### PR DESCRIPTION
**Pull request by oherrala**
This PR updates two dependencies: time to version 0.3 (yay!) and postgres to 0.19.

### CODE REVIEW

**Comment by bradfier** [comment]
Postgres 0.19 requires Rust 1.46 due to depending on https://github.com/rust-lang/rust/issues/49146

Other than bumping some very old dependencies (which I'm 100% on-board with!) does this upgrade buy us anything that would justify increasing our MSRV?

**Comment by oherrala** [comment]
@bradfier Oh, I didn't know about the version dependency.

But for me, the `master` branch doesn't build any more so I chose the easy way out by just updating the dependency:

```console
% cargo test
    Updating crates.io index
error: failed to select a version for the requirement `hmac = "^0.1"`
candidate versions found which didn't match: 0.11.0, 0.10.1, 0.10.0, ...
location searched: crates.io index
required by package `postgres-protocol v0.3.0`
    ... which is depended on by `postgres v0.15.2`
    ... which is depended on by `rouille v3.2.1 (/Users/oherrala/tmp/rouille)`
```

Is the postgres really needed at all? It feels like massive dependency to have for testing one example.

**Comment by bradfier** [comment]
> But for me, the master branch doesn't build any more so I chose the easy way out by just updating the dependency:

Thanks for this, it's frustrating that the version of HMAC that we depended on has been yanked, such is the state of dependencies in Rust I suppose!

> Is the postgres really needed at all? It feels like massive dependency to have for testing one example.

That's a fair point, I'd accept a PR that removes it (maybe swapping for some equivalent but lighter DB connector), or replaces that documentation example with something equivalent.

**Comment by bradfier** [comment]
@oherrala thanks for this! I ended up bumping the MSRV as debian dropped 1.41 and merged your updates as https://github.com/tomaka/rouille/commit/8075ccc3236b350c88ff7b387cd6130f9fe79caa

**Comment by oherrala** [comment]
@bradfier Thanks!

**Pull request closed without merging**
